version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dynamodb-lambdas"
s3_prefix = "dynamodb-lambdas"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
