AWSTemplateFormatVersion: 2010-09-09
Transform:
  - AWS::Serverless-2016-10-31

Description: >-
  DynamoDB Stack

Resources:
  cloudFormationDocsIndex:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: cloudFormationDocsIndex
      AttributeDefinitions:
        - AttributeName: group
          AttributeType: S
        - AttributeName: resource
          AttributeType: S
      KeySchema:
        - AttributeName: group
          KeyType: HASH
        - AttributeName: resource
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
  dynamoDbVpcEndpoint:
    Type: "AWS::EC2::VPCEndpoint"
    Properties:
      RouteTableIds:
        - Fn::ImportValue: !Sub "${vpcStackName}-private-route-table-id"
      ServiceName: !Sub "com.amazonaws.${AWS::Region}.dynamodb"
      VpcId:
        Fn::ImportValue: !Sub "${vpcStackName}-demo-vpc-id"

Parameters:
  vpcStackName:
    Description: Stack name of the demo VPC
    Type: String
    Default: lambdas-vpc
